[proxy_ru.domains]
donationalerts.com
ident.me

[proxy_ru.geosites]
2ch
tld-ru

[proxy_it.domains]
aeza.net
api.ipify.org
meduza.io
ntc.party
slickdeals.net

[proxy_it.geosites]
bestbuy
category-porn
discord
habr
linkedin
meta
netflix
openai
paypal
pinterest
rutracker
spotify
telegram
tiktok
twitter

[proxy_it.geoips]
facebook
netflix
telegram
twitter
